import {
  LayoutGrid,
  Zap,
  Bird,
  Type,
  CircleDot,
  Club,
  Hammer,
  Joystick,
} from "lucide-react";

export type GameDifficulty = "easy" | "medium" | "hard" | "expert";

export interface Game {
  id: string;
  title: string;
  description: string;
  icon: any;
  route: string;
  color: string;
  accent: string;
  category: "logic" | "arcade" | "puzzle" | "action" | "card" | "memory";
  status: "available" | "coming-soon" | "beta";
  tier: "free" | "premium";
}

export const games: Game[] = [
  {
    id: "mine-hunter",
    title: "Mine Hunter",
    description:
      "Find the hidden mines using the heat map before time runs out!",
    icon: "/mine.png",
    route: "/games/mine-hunter",
    color: "text-cyan-400",
    accent: "bg-cyan-400/10 border-cyan-400/20",
    category: "puzzle",
    status: "available",
    tier: "premium",
  },
  {
    id: "sudoku",
    title: "Sudoku",
    description: "Classic 9x9 grid puzzle. Logic-based number placement.",
    icon: "/sudoku.png",
    route: "/games/sudoku",
    color: "text-blue-500",
    accent: "bg-blue-500/10 border-blue-500/20",
    category: "logic",
    status: "available",
    tier: "free",
  },
  {
    id: "snake",
    title: "Snake",
    description: "Eat apples, grow longer, and avoid hitting the walls!",
    icon: "/snake.png",
    route: "/games/snake",
    color: "text-green-500",
    accent: "bg-green-500/10 border-green-500/20",
    category: "arcade",
    status: "available",
    tier: "free",
  },
  {
    id: "2048",
    title: "2048",
    description: "Join the numbers and get to the 2048 tile!",
    icon: "/2048.png",
    route: "/games/2048",
    color: "text-orange-500",
    accent: "bg-orange-500/10 border-orange-500/20",
    category: "puzzle",
    status: "available",
    tier: "free",
  },
  {
    id: "memory",
    title: "Memory",
    description: "Test your memory by matching pairs of cards.",
    icon: "/memory.png",
    route: "/games/memory",
    color: "text-pink-500",
    accent: "bg-pink-500/10 border-pink-500/20",
    category: "puzzle",
    status: "available",
    tier: "free",
  },
  {
    id: "f1-racing",
    title: "F1 Racing",
    description: "High speed racing. Avoid obstacles and set records.",
    icon: "/car.png",
    route: "/games/f1-racing",
    color: "text-red-500",
    accent: "bg-red-500/10 border-red-500/20",
    category: "action",
    status: "available",
    tier: "premium",
  },
  {
    id: "tetris",
    title: "Tetris",
    description: "Stack the falling blocks to clear lines.",
    icon: "/tetris.png",
    route: "/games/tetris",
    color: "text-purple-500",
    accent: "bg-purple-500/10 border-purple-500/20",
    category: "arcade",
    status: "available",
    tier: "premium",
  },
  {
    id: "tic-tac-toe",
    title: "Tic-Tac-Toe",
    description: "Classic X and O game. Play against AI or a friend.",
    icon: "/tic-tac-toe.png",
    route: "/games/tic-tac-toe",
    color: "text-cyan-500",
    accent: "bg-cyan-500/10 border-cyan-500/20",
    category: "logic",
    status: "available",
    tier: "free",
  },
  {
    id: "minesweeper",
    title: "Minesweeper",
    description: "Clear the board without detonating any mines.",
    icon: "/mine.png",
    route: "/games/minesweeper",
    color: "text-gray-400",
    accent: "bg-gray-500/10 border-gray-500/20",
    category: "logic",
    status: "available",
    tier: "premium",
  },
  {
    id: "breakout",
    title: "Breakout",
    description: "Smash all the bricks with the bouncing ball.",
    icon: Joystick,
    route: "/games/breakout",
    color: "text-yellow-500",
    accent: "bg-yellow-500/10 border-yellow-500/20",
    category: "arcade",
    status: "available",
    tier: "premium",
  },
  {
    id: "simon-says",
    title: "Simon Says",
    description: "Follow the pattern of lights and sounds.",
    icon: Zap,
    route: "/games/simon-says",
    color: "text-indigo-500",
    accent: "bg-indigo-500/10 border-indigo-500/20",
    category: "memory",
    status: "available",
    tier: "free",
  },
  {
    id: "flappy-bird",
    title: "Flappy Clone",
    description: "Navigate through the pipes. Don't crash!",
    icon: Bird,
    route: "/games/flappy-bird",
    color: "text-sky-500",
    accent: "bg-sky-500/10 border-sky-500/20",
    category: "arcade",
    status: "available",
    tier: "premium",
  },
  {
    id: "word-search",
    title: "Word Search",
    description: "Find hidden words in the letter grid.",
    icon: Type,
    route: "/games/word-search",
    color: "text-teal-500",
    accent: "bg-teal-500/10 border-teal-500/20",
    category: "puzzle",
    status: "available",
    tier: "free",
  },
  {
    id: "connect-four",
    title: "Connect Four",
    description: "Connect 4 discs in a row to win.",
    icon: CircleDot,
    route: "/games/connect-four",
    color: "text-amber-500",
    accent: "bg-amber-500/10 border-amber-500/20",
    category: "logic",
    status: "available",
    tier: "premium",
  },
  {
    id: "solitaire",
    title: "Solitaire",
    description: "Classic Klondike card game.",
    icon: Club,
    route: "/games/solitaire",
    color: "text-emerald-500",
    accent: "bg-emerald-500/10 border-emerald-500/20",
    category: "card",
    status: "available",
    tier: "premium",
  },
  {
    id: "whack-a-mole",
    title: "Whack-a-Mole",
    description: "Hit the moles before they hide again!",
    icon: Hammer,
    route: "/games/whack-a-mole",
    color: "text-orange-700",
    accent: "bg-orange-700/10 border-orange-700/20",
    category: "action",
    status: "available",
    tier: "free",
  },
];
